name: Story
description: "Feature addition to a Validated Product | parent: epic"
title: "[Story]: "
type: story
projects: ["INEOSDataScience/15"] # automatically add to this project
body:
  - type: markdown
    attributes:
      value: |
        Provide the following details to define the story:
  - type: textarea
    id: description
    attributes:
      label: Describe the story
      placeholder: what work do you intend to do to increment the epic?
    validations:
      required: true
