name: Auto Draft PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-draft-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set PR to draft
        if: github.event.pull_request.draft == false
        uses: actions/github-script@v7
        with:
          script: |
            console.log(`Attempting to convert PR #${context.issue.number} to draft...`);
            
            try {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                draft: true
              });
              
              console.log(`Successfully converted PR #${context.issue.number} to draft`);
            } catch (error) {
              console.error(`Error converting PR to draft:`, error);
              throw error;
            } 