name: Auto Draft PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-draft-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set PR to draft
        if: github.event.pull_request.draft == false
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            if (!pullRequest.draft) {
              await github.rest.pulls.convertToDraft({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
              });
              
              console.log(`Converted PR #${context.issue.number} to draft`);
            } 